name: flutter_sparkline
description: Beautiful sparkline charts for Flutter.
version: 0.1.0
homepage: https://github.com/tankaetzer/flutter_sparkline

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0"
